### ISSUE TITLE
Break time should not be added until user specify it

### ISSUE THREAD

**Issue by Flouss** [getmoro/moro#184]
Issue: If report is asked before the break time is elapsed, moro returns a wrong work time.
Example:
![conemu64_2018-05-13_19-09-47](https://user-images.githubusercontent.com/15911342/39970323-b7eb613a-56e9-11e8-8e63-1774b25a5c99.png)

Suggestion:
Do not count the break time until user add it manually.
This could be easily done by not adding default break duration to database.

**Comment by Flouss** [comment]
IMHO those two solutions would only go around the problem.

In a normal workflow the user should add the break duration manually after the break has passed, this will make the break duration more accurate and the total time worked more intuitive. And as a side effect this will also avoid the negative worked time.

**Comment by omidfi** [comment]
Bu the way users can set the default break to 0 if they want to be very precise. 

To me it's important that the default setting works for most of people, including myself :D, but special needs can be configired easily.

**Comment by Flouss** [comment]
I understand, what about not setting the break duration before the actual lunch break (1 p.m)?
Reports displayed before noon will not count the break duration and reports after noon will add the break duration to the total.

**Comment by Kuchenm0nster** [comment]
How about adding the break only if the work time exceeds a defined threshold?
If I work more than 6 hours i have to take a break. Don't know how many hours in other countries but a config setting for a threshold seems fine.

**Comment by Goatmaster** [comment]
I also have the problem that the time for making it a full day is shown wrong.

If I enter a break time for like 59minutes for the day (moro break 59) the time for the full day is not calculated again.

**Comment by hexsel** [comment]
Just a suggestion, why not add an optional command to mark start and end of break? it's a lot simpler for me to say "starting my lunch break" (and maybe a coffee break!) and "done my lunch break".  Doesn't have to be complicate, maybe 

    moro break start <optional name for the break?>
    moro break end
