### ISSUE TITLE
Announcement: Developing Moro further! 🎉

### ISSUE THREAD

**Issue by albacoretuna** [getmoro/moro#273]
**Good news!**

 We have formed a team to work on Moro. 🎉🎉🎉

**What will change:** 
- An optional web interface where users can sync their reports, edit them and even do time tracking when away from the command line. 
- The license will be changed from MIT to AGPL 
- Moro will remain free an open source, but the optional hosted cloud sync will cost few euros per month. 

**Wanna help?** 
If you have any feature requests or ideas please let us know. We'd love to have a group of beta testers.

**Comment by jpaulin** [comment]
Idea: in addition to hours worked, allow automatically monitoring a software project for one metric: original lines added. So the module would add also a arbitrary extra number which basically is a measure of original productivity on a project. So you couldn't bloat the number by adding copy-paste extra code, but the fingerprint is calculated somehow comparing the code to existing solutions.
